version: "3"
services:
  nginx:
    image: springboot-nginx:0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/j3b308.p.ssafy.io:/var/www/j3b308.p.ssafy.io
      - /var/www/image:/var/www/image
    depends_on:
      - docker-springboot
  docker-springboot:
    build: .
    volumes:
      - /var/www/image:/resource/image
    expose:
      - 8080
